.\" Manpage for ipfsphere.sh

.\" Contact: Piotr Trybisz (ptrybisz@gmail.com)

.\" Created on: 17.05.2023

.\" Last modified: 17.05.2023

.\" Version: 0.1

.\" Description: decentralised chat using ipfs

.\"

.\" Licensed under GPL (see /usr/share/common-licenses/GPL for more details

.\" or contact the Free Software Foundation for a copy)

.TH IPFSPHERE.SH 1 "17.05.2023" "0.1" "decentralised chat using ipfs"

.SH NAME

ipfsphere.sh \- decentralised chat using ipfs

.SH SYNOPSIS

.B ipfsphere.sh

[OPTION]

.SH DESCRIPTION

This script provides a decentralised chat using IPFS (InterPlanetary File System). It allows users to communicate in different channels and exchange messages in a distributed manner.

.SH OPTIONS

.IP "-h"

Displays the help message, providing information about the available options and their usage.

.IP "-v"

Displays version information and checks for updates. If a new version is available, it prompts the user to update.

.IP "-r"

Resets the ipfsphere application, deleting all data, including messages and certificates.

.IP "-s"

Shuts down the ipfsphere application by stopping the IPFS daemon.

.SH AUTHORS

Piotr Trybisz (ptrybisz@gmail.com)

.SH REPORTING BUGS

Bugs can be reported using Issues on GitHub: <https://github.com/PetrusTryb/ipfsphere/issues/>

.SH COPYRIGHT

This script is licensed under the GPL (GNU General Public License). Please refer to /usr/share/common-licenses/GPL or contact the Free Software Foundation for more details.

.SH "SEE ALSO"

.IP "\fBipfs\fR(1)"

.IP "\fBdialog\fR(1)"

.IP "\fBcurl\fR(1)"

.IP "\fBopenssl\fR(1)"

.IP "\fBgrep\fR(1)"

.IP "\fBawk\fR(1)"
